### ISSUE TITLE
Fix 404 error view for unexpected term pass into url

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#10]
Fix 404 error view when unexpected term pass into URL

![Awesome6](https://user-images.githubusercontent.com/43210406/60752434-3a899b00-9fe3-11e9-8fc3-b7e11b14d0b6.png)

**Comment by Komal-sharma-2712** [comment]
This issue is fixed now so I am closing this issue:

![image](https://user-images.githubusercontent.com/63539748/190344723-29b45bcb-a922-4263-8dcc-9d195a30ba3c.png)
