### ISSUE TITLE
Searching keyword not passed in url or stay saved in search bar

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#11]
### Observe that search key will not found in the URL or also not stay saved in the search bar.

**Comment by Komal-sharma-2712** [comment]
This issue is fixed now  so I am closing this issue:

![image](https://user-images.githubusercontent.com/63539748/190347757-ebc6bcc4-a322-465d-8146-e78edb67db94.png)
