### ISSUE TITLE
wrong screenshot added for customer creation at admin end

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#19]
![Screenshot_277](https://user-images.githubusercontent.com/43210406/107369873-48c96280-6b08-11eb-8c40-31b39707f45f.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated the wrong text and screenshot for the same.

**Comment by vaishaliwebkul** [comment]
fixed
