### ISSUE TITLE
update branding.html as per the branding section

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#20]
https://docs.uvdesk.com/uvdemo/settings/branding.html

currently, inside branding Helpdesk & Support Center option available, and further step need to describe in detail.
![Screenshot_278](https://user-images.githubusercontent.com/43210406/107370928-9d211200-6b09-11eb-8648-6a23da06dc9b.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

All new screenshots updated for branding section.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
broken image is showing here https://prnt.sc/104tfz2 on branding.html

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev
> broken image is showing here https://prnt.sc/104tfz2 on branding.html

Updated.

**Comment by vaishaliwebkul** [comment]
fixed
