### ISSUE TITLE
update template.html

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#21]
https://docs.uvdesk.com/uvdemo/settings/template.html

![Screenshot_279](https://user-images.githubusercontent.com/43210406/107372242-369cf380-6b0b-11eb-9674-77066735a247.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated

**Comment by vaishaliwebkul** [comment]
fixed
