### ISSUE TITLE
update mailbox.html

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#25]
https://docs.uvdesk.com/uvdemo/settings/mailbox.html

Here, the wrong screenshot added
![Screenshot_280](https://user-images.githubusercontent.com/43210406/107375894-40c0f100-6b0f-11eb-90a6-0d05e2dbc7e2.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

New Screenshot added.

**Comment by vaishaliwebkul** [comment]
fixed
