### ISSUE TITLE
update workflow.html

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#26]
https://docs.uvdesk.com/uvdemo/productivity/workflow.html

Task is not exist right now

![Screenshot_281](https://user-images.githubusercontent.com/43210406/107376354-ce044580-6b0f-11eb-871d-d9a27d6015d7.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
update screenshot also, as task is showing https://prnt.sc/104rua4

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated screenshot for this.

**Comment by vaishaliwebkul** [comment]
fixed
