### ISSUE TITLE
add doc which explain steps to configure & setup Docker

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#27]
add steps to configure & setup Docker in doc

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Added https://prnt.sc/103tmi6 here.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
add docker option inside navbar menu also https://prnt.sc/104ryjq

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated navbar with docker doc link.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
when clicking on "docker your application" the docker menu should be listed below instead of directly open the docker.html

**Comment by Komal-sharma-2712** [comment]
This issue is fixed now docker steps and docker option added to the menus list:

![image](https://user-images.githubusercontent.com/63539748/190348922-f1893cc3-17da-4c5e-912c-dffd00699e8d.png)
