### ISSUE TITLE
Search term cannot be select by helping of "keypress"

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/uvdesk.github.io#9]
### When search for the term and select better one by keyboards key, no event occurs.

![Awesome5](https://user-images.githubusercontent.com/43210406/60752018-58540180-9fdd-11e9-8ab7-6b70c107657a.png)

**Comment by Komal-sharma-2712** [comment]
This issue is fixed now so I am closing this issue:

![image](https://user-images.githubusercontent.com/63539748/190351376-03129cbf-30ca-4e47-9995-a808cc072506.png)
